# Предсказание патагенности бактерии по данным NGS-секвенирования

**NB. Данный документ может редактироваться и дополняться в течение выполнения проекта**

## Техничекие детали

Вам в распоряжение предоставлен удаленный сервер bioinf0X.bioinf.me, где X -- номер, который соотвестует вашей команде. Вы можете подключиться к нему используя ssh, где user0Y и bioinf0X -- ваш пользователь и ваша команда соотвественно:
```
ssh user0Y@bioinf0X.bioinf.me
```

На данном кластере доступны вам доступные некоторые ресурсы: 16GB оперативной памяти, 100ГБ дискового пространства, быстрый интернет и 4 процессора.

Для вашей команды также создана общая папка `/data/`, **внутри которой** на данный момент лежат папка `small_dataset`, которая содержит fastq-данные секвенирования бактерий:

```{bash }
ls small_dataset | head -2
```


```{bash }
ls small_dataset/PRJDA40637
```

Также доступен файл `info.tsv`, содержащий информацию об этих файлах и их соответствие патогенным и непатогенным бактериям.

```{bash }
head info.tsv
```

Также вам будет доступна web-версия Rstudio на этом сервере, доступ к ней можно получить в браузере https://bioinf0X.bioinf.me/rstudio, логин и пароль для авторизации совпадают и именем пользователя и паролем для ssh.

## Библиотеки

Для вашего удобства на кластере уже установлены NCBI Eutils https://www.ncbi.nlm.nih.gov/books/NBK25500/ (она понадобиться вам, чтобы скачивать бактериальные геномы):

```
$ efetch --help | head
efetch 6.10

Format Selection

  -format        Format of record or report
  -mode          text, xml, asn.1, json

Direct Record Selection

  -db            Database name

```

И seqan_mason (она понадобится вам, чтобы генерировать риды по бактериальному геному).

```
$ seqan_mason
Mason - A Read Simulator
(c) 2010 by Manuel Holtgrewe

Usage: mason illumina [OPTIONS] [SEQUENCE.fasta]
       mason 454 [OPTIONS] [SEQUENCE.fasta]
       mason sanger [OPTIONS] [SEQUENCE.fasta]

Call with 'mason READS-TYPE --help' to get detailed help.

```

## Ожидамая работа над проектом

Мы хотим обучить классификатор патогенности/непатогенности бактерии по данным NGS-секвенирования, входными данными являются данные paired-end секвенирования -- два файла парных ридов.

Папка small_dataset содержит пример таких данных, на которых вы можете начать обучать классификатор, пока другая часть команды занимается получением данных из базы данных IMG https://img.jgi.doe.gov/cgi-bin/m/main.cgi. Эта база данных содержит аннотацию о геномах различных микробов. Обращаю ваше внимание, что в нашей работе нас будут прежде всего интересовать **бактериальные геномы**, потенциальным хостом которых может являться **человек**.

После того, как вы получить из IMG ссылки на геномы, которые вам нужны, вы сможете их скачать, используя NCBI eutils.

После того, как вы скачаете fasta файлы с геномами, вы должны нагенерировать риды секвенирования секвенатора Illumina. Для этого вы должны воспользоваться программой seqan_mason, и эти данные затем будут подаваться на вход обучения вашего классификатора.

## Классификатор

Ожидается, что классификатор должен говорить, является бактерия патогенной или нет, однако имеет смысл разбить данную задачу на две. Для начала стоит написать классификатор отдельных ридов. Мы подаем рид на вход, и говорим откуда это рид пришёл -- из патогенной бактерии, или не патогенной бактерии. А затем можно написать классификатор, который бы агреггировал суммарную информацию классифицированных ридов.

Риды -- не очень удобный инструмент классификации, поэтому следует определить некоторые признаки у ридов: мы будем смотреть только на признаки связанные с последовательностями нуклеотидов: вхождения определенных K-mer и Spaced words.

**Описание этих признаков появятся чуть ниже. **


## Оценка проекта

Я буду отслеживать вашу работу в течение хакатона, и буду следить за тем, какие команды сильнее продвинутся по проекту. Если окажется, что будут команды, которые успеют закончить проект целиком -- я буду оценивать их классификаторы, на своём датасете основанном на IMG, используя 10 fold cross validation, буду смотреть на accuracy и ROC curve, если ваши классификаторы смогут их построить.

